export const CARD_VERSIONS = [
  { id: "v1", name: "V1 Signature" },
  { id: "v2", name: "V2 Bande latérale" },
  { id: "v3", name: "V3 Dark élégante" },
  { id: "v4", name: "V4 Bicolore" },
  { id: "v5", name: "V5 Orange bold" },
  { id: "v6", name: "V6 Géométrique" },
  { id: "v7", name: "V7 Ligne fine" },
  { id: "v8", name: "V8 Shadow" },
  { id: "v9", name: "V9 Gradient" },
  { id: "v10", name: "V10 Typo" },
  { id: "v11", name: "V11 Arrondi XL" },
  { id: "v12", name: "V12 Dégradé orange" },
  { id: "v13", name: "V13 Sombre orange" },
  { id: "v14", name: "V14 Bordure" },
  { id: "v15", name: "V15 Texturée" },
  { id: "v16", name: "V16 Diagonal" },
  { id: "v17", name: "V17 Initiales" },
  { id: "v18", name: "V18 Carré central" },
  { id: "v19", name: "V19 Compact" },
  { id: "v20", name: "V20 Premium noir" },
];
